### ISSUE TITLE
Apply Repo Guidelines

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW-Website#1]
Per https://github.com/edgi-govdata-archiving/overview/blob/main/repo_guidelines.md

* [x] Use only one Readme
* [x] Apply license block to Readme
* [x] Add links to Conduct
* [x] Add Contributing guidelines
* [x] Configure issue labels
* [x] Configure stalebot
* [x] Make sure main branch is `main`
* [x] Add content to Readme including description and how to contribute

**Comment by Frijol** [comment]
@ozzmotic the current license is MIT, it looks like this is a default from Gatsby? EDGI typically uses GPLv3 for code – is it ok if I change it, or did you pick MIT?

**Comment by plastichotsprings** [comment]
I didn't pick it -- yes, feel free to change the license!
