### ISSUE TITLE
Make a 404 page

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW-Website#10]
It would be cute to use one of our memes from over on our social channels

**Comment by ericnost** [comment]
Section 404 of the Clean Water Act is a huge part of EPA's work (authorization to fill wetlands) and though it's not something we have data on, it is environmental enforcement and compliance. I've always wondered about how to connect it to 404 page status https://www.epa.gov/cwa-404/permit-program-under-cwa-section-404

**Comment by Frijol** [comment]
oh I love this! I was hoping we could do something clever like that
