### ISSUE TITLE
Integrate the visualization into the website

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW-Website#101]

**Comment by plastichotsprings** [comment]
![image](https://user-images.githubusercontent.com/4603869/93393916-57556b80-f841-11ea-8a5e-fbc6ee013fd9.png)

**Comment by plastichotsprings** [comment]
on hover: 
![image](https://user-images.githubusercontent.com/4603869/93393958-663c1e00-f841-11ea-8897-4b7f7a3de00b.png)

**Comment by Frijol** [comment]
@crgreenleaf for your reference, I asked Alex to screenshot the visualization as it stands so that you can have it in mind when thinking about the homepage design in https://github.com/edgi-govdata-archiving/EEW-Website/issues/97

**Comment by Frijol** [comment]
closed in https://github.com/edgi-govdata-archiving/EEW-Website/pull/106
