### ISSUE TITLE
Make github pages account 

### ISSUE THREAD

**Issue by mraisle** [edgi-govdata-archiving/EEW-Website#12]
Hey! Would love to have access to a github pages account so I can try to publish some reports. 
Here's the link - https://pages.github.com/
If you would share with me the login info on slack (if needed??) once it is done that would be great!

**Comment by Frijol** [comment]
I think the existing organizational github account is all you need, actually. If you make a repo and go to its settings page, you just pick a branch to make the Github Pages branch. If you go into the settings of an EEW repo, can you see this?

![Screen Shot 2020-08-12 at 2 18 52 PM](https://user-images.githubusercontent.com/454690/90069238-e30a3400-dca6-11ea-8e6a-d4138906b1fb.png)

So next step is to make repo(s)? for the reports. Is there already something we can work with? (Do you need me to set up repos/repo access?)

**Comment by mraisle** [comment]
great! I was able to navigate to this! It looks like I also have access to start a new repo. I'll move the repo I'm working out of over to an EDGI one later today. Thanks! I'll close this issue :)
