### ISSUE TITLE
Finalize congress.json

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW-Website#125]
Moving conversation from #124 into a new issue so that I can merge the PR @calderEDJ

### Some notes on the unresolved pieces: 

1. "02" vs "2" won't matter for code/parsing purposes here, so go ahead and pick your preferred format. It will show up like this: ![Screen Shot 2020-09-28 at 2 51 57 PM](https://user-images.githubusercontent.com/454690/94490110-a5039980-019a-11eb-8068-d7ee4fd63115.png)
2. Can you say more about subcommittees? Is this an additional field we need to add here & render in the hovertext box? Or is it fine to leave that just in the report?
3. Please do add the URLs of the reports. The "status" box is used to make any report marked "notCompleted" unclickable, so there's no danger they'll be released early.

### A couple more thoughts:
1. Are the committee members in any particular order? It will render in whatever order they are in in the JSON file.
2. Can you request a second review from someone to check your data? Might be a good task for the new #small_tasks channel

_Originally posted by @Frijol in https://github.com/edgi-govdata-archiving/EEW-Website/pull/124#issuecomment-700308107_

**Comment by ericnost** [comment]
> "02" vs "2" won't matter for code/parsing purposes here, so go ahead and pick your preferred format

If we go the interactive map route, the districts will need to be in the 02, 00, etc. format to match the spatial data format. So, 02 instead of 2, and 00 for WY and DE reps which have no districts per se.

**Comment by Frijol** [comment]
Let's go ahead and use that "02" format then for future compatibility. @ericnost would you also like us to pre-input "00" for "district" under the senate json objects? Will need to make a minor code adjustment to support but that's no issue

**Comment by Frijol** [comment]
@ericnost and @calderEDJ here's a pull request that adds support for a "00" district field for senate, feel free to merge (https://github.com/edgi-govdata-archiving/EEW-Website/pull/128)

Not an issue for the website but @ericnost just flagging that at-large house reps are also "00" at the moment, e.g. Peter Welch

**Comment by calderEDJ** [comment]
Ok, I'm not really clear on what #128 is all about, but I'm going to start adding the report card links into congress.json using this format decided on in yesterday's meeting: https://edgi-govdata-archiving.github.io/CD-report/CA36_2020

**Comment by Frijol** [comment]
Resolved in https://github.com/edgi-govdata-archiving/EEW-Website/pull/152
