### ISSUE TITLE
Finalizing EEW Website and Getting it live at environmentalenforcementwatch.org Oct 14

### ISSUE THREAD

**Issue by lesliealanis** [edgi-govdata-archiving/EEW-Website#127]
**Website Layout**
- [x] Make a final decision on all the design change suggestions @Frijol / group
- [x] Move all of the existing items around into the layout we decide on as a group @Frijol 

**Building Website Content**
- [x] Check over/improve styling/aesthetics
- [x] Update video? @calderEDJ @crgreenleaf 
Map:
- [x] Map: seems like we’re going to want one, is it static or interactive? Where does it go?
- [x] Make the map @ericnost 
- [x] Put the map where it’s supposed to go @Frijol 
Adding Links:
- [x] Create/place a “share to twitter” section (maybe just a link) @Frijol 
- [x] Create/place a “write to your reps” section (maybe just a link) @Frijol 
- [x] Add links to reports into congress.json @calderEDJ 
Other issues:
- [x] More stuff? Technical issues that may arise & need fixing? @Frijol 

**Finalizing Website: Complete Website Content**
- [ ] Get website copy (all of it) reviewed
- [x] Make google with the website copy for others to review by page @calderEDJ could you make that asap?
- [x] Make complete list of folks who contributed to EEW for website- we can draw from this list, https://github.com/edgi-govdata-archiving/EEW_Planning @saraannwylie started draft here: https://docs.google.com/document/d/1YgKXoDe3gSi6Q6a0Q8U2zaBUSVWeBRTOlib49-u6fy4/edit. flagged for slack review here: https://edgi.slack.com/archives/CKN6FMX42/p1601434745069200
- [ ] Implement changes to final website copy
- [ ] SysAdmin stuff to get the website live at the URL (I think this is straightforward but I’m not certain) @Frijol

**Comment by saraannwylie** [comment]
Flagging for @Frijol that we also need to discuss whether registration for the release event happens through the website, since the event will be just a week after the website is live we probably registration to happen earlier @crgreenleaf, it could happen through the EDGI website or through the static site? Would be good if we can make a plan by Oct. 2nd.

**Comment by saraannwylie** [comment]
Flagging for @Frijol and @mraisle that we need to discuss what/how the reportcards will be released under embargo on the 14th? Will we be sharing the website link just with a subset of journalists? Is it feasible to embargo a website or password protect it?

**Comment by lesliealanis** [comment]
@saraannwylie, @Frijol mentioned that instead of making these tasks into a checklist we should make them into issues, which method do we prefer?

**Comment by Frijol** [comment]
I'd much prefer we separate out each item as its own issue – that way we can have individuals assigned to each issue, and conversations relevant to the issue can occur there without crossing over each other + notifying folks who aren't a part of that item.

@saraannwylie re the questions of partial release and password protection – these are things that are technically possible but that haven't been in the plan, so I don't think there is time or capacity for me to do them. Event registration is no big deal to add to the site, but my understanding was that it was an event concurrent with website release, so not sure if it makes sense.

**Comment by Frijol** [comment]
Closing, all unfinished items have their own issues
