### ISSUE TITLE
Image in header looks a little messy

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW-Website#151]
Is this the final logo? Pixels look kinda weird along this top-of-the-pupil curve: 
![Screen Shot 2020-10-01 at 12 24 53 PM](https://user-images.githubusercontent.com/454690/94854102-3d8b5b00-03e1-11eb-9aac-d71a007a2af1.png)

**Comment by calderEDJ** [comment]
all of our final logos are here: https://drive.google.com/drive/u/0/folders/195Fn0G_EAFrFFJ6pDAZ-1nilyj5_8lra

**Comment by Frijol** [comment]
Thanks!
