### ISSUE TITLE
Add placeholder for Summary Enforcement Report to the reports page

### ISSUE THREAD

**Issue by saraannwylie** [edgi-govdata-archiving/EEW-Website#154]
Need to have a space for the enforcement report summary on this page:https://edgi-govdata-archiving.github.io/EEW-Website/reports

Should discuss will this be a link to EDGI website that hosts the report as pdf?
Or will we embed pdf in this page?

Might also add key highlights from that report into the text somewhere?

**Comment by leiffredrickson** [comment]
We could put the report on both sites couldn't we? If we have to choose, I'd say put it on the EEW site and link to it on EDGI

**Comment by Frijol** [comment]
Placeholder exists now (https://github.com/edgi-govdata-archiving/EEW-Website/issues/190 for placement of the text)
