### ISSUE TITLE
Add page for EEW events?

### ISSUE THREAD

**Issue by saraannwylie** [edgi-govdata-archiving/EEW-Website#155]
Current design doesn't have a page for EEW events. I suggest bringing that page back, 

- [ ] with the circle diagram,

- [x]  adding the graphics and info about the release event--so when the websites goes live it's describe there.

- [x] putting links in it to the blog about the prior events?
https://envirodatagov.org/practicing-our-right-to-know-together-review-of-eew-congressional-report-card-workshops-to-date/

- [ ] Putting a request form on that page for people who might want to host an EEW event.

**Comment by Frijol** [comment]
I'm a bit confused about this, we have a page live called "Events" that has the info about EEW events. Leslie has just done a redesign here https://github.com/edgi-govdata-archiving/EEW-Website/issues/147 about putting in links to prior events. Circle diagram is currently on the reports page.

Concerned I may not be understanding the need you're expressing, would you mind working with @lesliealanis to see if there is more info she needs to incorporate into the page?

**Comment by saraannwylie** [comment]
@Frijol I see the events page now! I've no idea how I missed it earlier!
