### ISSUE TITLE
Link to COVID Report and other EEW reports on the website

### ISSUE THREAD

**Issue by saraannwylie** [edgi-govdata-archiving/EEW-Website#156]
We need a place to put other reports that come out of EEW on this website? 
Perhaps as dropdown under Reports? 
Or under the Press make a drop down "publications"

I'm thinking particularly of the COVID report and the BioLab fire blog.

https://envirodatagov.org/bio-labs-toxic-record-presages-chlorine-fueled-fire-following-hurricane-laura/

https://envirodatagov.org/more-permission-to-pollute-the-decline-of-epa-enforcement-and-industry-compliance-during-covid/

**Comment by Frijol** [comment]
I like the idea of having a Publications section on the Press page. We should think about this more in the long term but that's an easy fit for our current trajectory
