### ISSUE TITLE
Making the event screenshot smaller on the events page

### ISSUE THREAD

**Issue by lesliealanis** [edgi-govdata-archiving/EEW-Website#171]
Events Page ( #161 ) the screenshot is too big and we need to shrink it

**Comment by Frijol** [comment]
![Screen Shot 2020-10-06 at 10 47 51 AM](https://user-images.githubusercontent.com/454690/95240527-646ed600-07c1-11eb-99f5-cdfb46c180aa.png)

It looks good to me, what are you imagining?

**Comment by lesliealanis** [comment]
@Frijol it looked too big before when the youtube video was smaller but it looks great now.
