### ISSUE TITLE
Design consideration: text too redundant?

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW-Website#176]
![Screen Shot 2020-10-07 at 11 51 51 AM](https://user-images.githubusercontent.com/454690/95374710-89337e00-0893-11eb-86b8-98e7c0025ce0.png)

We have some very similar call-to-action text one right after the other in this screenshot. Revise?

**Comment by lesliealanis** [comment]
Linking this issue #155, @saraannwylie mentioned adding something like, "Interested in hosting an event with EEW? Contact us at _____"

**Comment by lesliealanis** [comment]
@Frijol Should I go ahead and get rid of, "together we can use publically available data..." and replace it with "Interested in hosting an event with EEW? Contact us at _____"

**Comment by Frijol** [comment]
Yeah that sounds great!

**Comment by lesliealanis** [comment]
@Frijol @saraannwylie I'm not sure if we decided on a MailChimp form, a google form, or the eew email

**Comment by Frijol** [comment]
Let's go with EEW email for now since that is simplest. If the team decides an embedded form/signup would be better, that can be a new Issue
