### ISSUE TITLE
Need reviewers for EEW web copy ASAP

### ISSUE THREAD

**Issue by calderEDJ** [edgi-govdata-archiving/EEW-Website#177]
Please review the web page copy and check the box once you've reviewed a page. If you can't review every page please assign another reviewer.

- [x] [Home Page](https://docs.google.com/document/d/1Bde1qfxshfwk9y7S2NgJnpFm5VGLYzKuHOqucWjOdEs/edit)
- [x] [About Page](https://docs.google.com/document/d/1y2asMEiGDwDZ5rsits1cK7W-UqVnxMNGXFIDVVWozlk/edit#)
- [x] [Reports Page](https://docs.google.com/document/d/1qY6H5chhdedBP5OvZOcDDJQpOw3GdFdidEdaY5uWD_8/edit#)
- [x] [Events Page](https://docs.google.com/document/d/1gIOIgR13-r7fR54-eEJVvEyfh2-7Tm_STElVg0U7bsI/edit#)

**Comment by lesliealanis** [comment]
I checked the home page and the reports page, I don't want to check the box yet because they might need others to check them as well

**Comment by Frijol** [comment]
#179 should get resolved through this

**Comment by Frijol** [comment]
so will https://github.com/edgi-govdata-archiving/EEW-Website/issues/188

**Comment by Frijol** [comment]
Can we close this issue @calderEDJ ?
