### ISSUE TITLE
Typo on About EWW

### ISSUE THREAD

**Issue by jessvarner** [edgi-govdata-archiving/EEW-Website#179]
"Both projects used data from EPA’s Enforcement and Compliance History Online (ECHO) database."

Should be "the EPA's"

**Comment by Frijol** [comment]
@lesliealanis does #200 resolve this?

**Comment by calderEDJ** [comment]
Yes, @Frijol #200 does resolve this. I'll close this issue

**Comment by Frijol** [comment]
ha, actually the protocol is to link the issue, but it doesn't get closed until the change merges
