### ISSUE TITLE
Explanatory text around the Core Contributors section?

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW-Website#188]
* In addition to our graphic, we should have some text about what the "areas of care" are/mean. @calderEDJ says @saraannwylie already has some text for this, so need to get it onto the page
* I retitled this section "Core Contributors" because it used to be "Participants" but I didn't want to exclude all of our workshop participants from consideration, is this a good title?

**Comment by calderEDJ** [comment]
I like "core contributors" as the section title. And the domains of care copy is included in the about page copy google doc.

**Comment by Frijol** [comment]
Should stay open until the pull request with the changes merges (and thus the issue is resolved on main)! The pull request is already linked, so it will close this automatically when it merges
