### ISSUE TITLE
Add a section about Jupyter Notebooks

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW-Website#189]
* @maalvikabhat what does it say?
* @lesliealanis where on the Events page does it go?

**Comment by Frijol** [comment]
@calderEDJ has a plan for this

**Comment by Frijol** [comment]
@calderEDJ is this now completed in the current version of the events page? (Look at deployed site https://edgi-govdata-archiving.github.io/EEW-Website/events)

**Comment by calderEDJ** [comment]
This is in progress here: https://docs.google.com/document/d/1xw4EfJGzRgNDpVxhu4TJOSGkkTg4vfE7-LX6F4xSmyg/edit
It will be finalized tomorrow

**Comment by Frijol** [comment]
Did this get merged in a pull request?
