### ISSUE TITLE
Changing Vermont from green to purple in the Reports page

### ISSUE THREAD

**Issue by lesliealanis** [edgi-govdata-archiving/EEW-Website#215]
Changing Vermont from green to purple in the Reports page since green is associated with the green party and VT is independent.

**Comment by Frijol** [comment]
Purple options:

190b28
bc7c9c

**Comment by lesliealanis** [comment]
I like bc7c9c!

**Comment by Frijol** [comment]
Here are some samples, really hard to get a value match w the red and blue

bc7c9c

![Screen Shot 2020-10-15 at 9 34 14 AM](https://user-images.githubusercontent.com/454690/96159784-e9e13d00-0ec9-11eb-9803-b4d6f4fd50a7.png)


190 etc is too dark

cebacf

![Screen Shot 2020-10-15 at 9 36 11 AM](https://user-images.githubusercontent.com/454690/96159808-f2397800-0ec9-11eb-9392-34393df06f27.png)


d4c5e2

![Screen Shot 2020-10-15 at 9 38 13 AM](https://user-images.githubusercontent.com/454690/96159953-2a40bb00-0eca-11eb-8a55-7bb0cf090cad.png)

d4b2d8

![Screen Shot 2020-10-15 at 9 39 21 AM](https://user-images.githubusercontent.com/454690/96160077-52301e80-0eca-11eb-93e3-98f9892f393d.png)

e2a3c7

![Screen Shot 2020-10-15 at 9 39 21 AM](https://user-images.githubusercontent.com/454690/96160220-83a8ea00-0eca-11eb-90ec-f6ec220bc877.png)

42033D

![Screen Shot 2020-10-15 at 9 41 31 AM](https://user-images.githubusercontent.com/454690/96160298-9d4a3180-0eca-11eb-8555-df84078c31dd.png)

B784A7
![Screen Shot 2020-10-15 at 9 43 26 AM](https://user-images.githubusercontent.com/454690/96160488-e13d3680-0eca-11eb-92a8-3d8db6aea352.png)

AC7299
![Screen Shot 2020-10-15 at 9 44 27 AM](https://user-images.githubusercontent.com/454690/96160613-0c278a80-0ecb-11eb-8613-166b7355bf9d.png)


OO here we go

9A77BB
![Screen Shot 2020-10-15 at 9 47 01 AM](https://user-images.githubusercontent.com/454690/96160862-61fc3280-0ecb-11eb-8de9-0e3b3cc54d15.png)
