### ISSUE TITLE
improve resolution of the circle diagram on reports page

### ISSUE THREAD

**Issue by saraannwylie** [edgi-govdata-archiving/EEW-Website#228]
Would be good to have this not be fuzzy?

https://edgi-govdata-archiving.github.io/EEW-Website/static/7c44752a01f4649281c85921da6b8dba/68de2/report-card-tracker.png

**Comment by saraannwylie** [comment]
actually closing this I think it's just something weird with how it looked on chrome with my browser settings.

**Comment by Frijol** [comment]
Oh yeah, sometimes they look odd while they're still loading
