### ISSUE TITLE
Rename gh-pages branch?

### ISSUE THREAD

**Issue by lightandluck** [edgi-govdata-archiving/EEW-Website#260]
So we've successfully migrated to our own servers in #258, but we still have a page at https://edgi-govdata-archiving.github.io/EEW-Website/. This is because we are still using a `gh-pages` branch which automatically sets up the page.

Do we still want this? If not, we'll have to rename the branch to something else and update our Github actions. (I didn't realize before that `gh-pages` branch automatically sets up the page.)

**Comment by Frijol** [comment]
Ha, what a funny problem to have. We should probably rename the branch. (Have we already updated the readme to clarify staging vs deployment?)

**Comment by lightandluck** [comment]
Ok, I just realized this might also be an issue with the action that builds the site. I'll have to look into this later. 

Thanks for the reminder about the readme! Will open an issue for it.
