### ISSUE TITLE
Translate each member's rank for Spanish

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW-Website#266]
This is great! We also need a translation for each member's rank (Chair vs Member)

![Screenshot 2021-02-02 105117](https://user-images.githubusercontent.com/454690/106648069-a0822f80-6544-11eb-9cd9-e6f4244e0d31.png)

Edit to https://github.com/edgi-govdata-archiving/EEW-Website/blob/main/src/components/congress/congress.js#L126

_Originally posted by @Frijol in https://github.com/edgi-govdata-archiving/EEW-Website/pull/265#issuecomment-771118730_

**Comment by lesliealanis** [comment]
member = miembro and

**Comment by lesliealanis** [comment]
Hi @shansen5 , it it's not too much of a hassle here are the translations for those
chair = presidente
ranking member = miembro de mayor rango
member = miembro
