### ISSUE TITLE
Clarify democratizing data link language

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW-Website#269]
Might want to have more clarity around which reports have been translated, it's non-obvious that the summary report is not translated but the individual reports are. Consider adding "ver el resumen del informe (en ingles)" to the summary report line & "haga clic... en espanol" in the directions for the data visualization

* [x] Translate
* [ ] Implement on site

**Comment by lesliealanis** [comment]
Just for reference: staging bilingual reports page: https://staging.environmentalenforcementwatch.org/reports-es/

**Comment by lesliealanis** [comment]
@Frijol Agreed,  @shansen5 if we have the capacity we should replace "Resumen del Informe" with "Resumen del informe (en ingles)" 
and 
replace "haga clic para abrir un informe completo sobre la aplicación de la EPA en el distrito o estado del representante" with "haga clic para abrir un informe completo sobre la aplicación de la EPA en el distrito o estado del representante en español:"
