### ISSUE TITLE
Continuous integration for deploy

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW-Website#27]
New commits to `main` should trigger gh-pages deployment

**Comment by Frijol** [comment]
Looking to use Circle CI for this, docs @ https://circleci.com/docs/2.0/deployment-integrations/

**Comment by Frijol** [comment]
Too confusing, this Github Actions continuous deployment looks simpler: https://medium.com/front-end-weekly/ci-cd-with-github-actions-to-deploy-on-github-pages-73e225f8f131

**Comment by Frijol** [comment]
Used this [example](https://github.com/ShilpiMaurya/git-action-playground/blob/master/.github/workflows/playgroung.yml) and these docs:

https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow

https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

**Comment by Frijol** [comment]
I guess we need a merge to `main` in order to test this.

**Comment by Frijol** [comment]
I think it didn't work: https://github.com/edgi-govdata-archiving/EEW-Website/actions

**Comment by Frijol** [comment]
Ok, log file basically runs and builds fine but cancels because it doesn't have git ID configured. I think it needs this: https://github.com/marketplace/actions/configure-git-credentials

**Comment by Frijol** [comment]
should also add the badge associated with the github action to the readme when it's ready

**Comment by Frijol** [comment]
Badge: https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#adding-a-workflow-status-badge-to-your-repository

I guess we should have docs that tell how to manually deploy (`npm run deploy`) as well as noting what file & trigger are in play for auto deployment + to look in actions tab to debug?

**Comment by plastichotsprings** [comment]
Fixed in https://github.com/edgi-govdata-archiving/EEW-Website/commit/7d4ee836b3b0009ec686162d0d67c83c2d37814a and https://github.com/edgi-govdata-archiving/EEW-Website/commit/88ade35a353436dab2fbd747736afbe62f7bf9be
