### ISSUE TITLE
Prettier button

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW-Website#270]
![image](https://user-images.githubusercontent.com/454690/106657292-b1d13900-6550-11eb-8cec-26a0ab9444a8.png)
 spacing is a bit funny, play with this more? @shansen5 is this something you're already doing? If not I'm happy to

**Comment by shansen5** [comment]
I'll take it.

**Comment by lourdesvera** [comment]
@shansen5 hows this going?

**Comment by Frijol** [comment]
Also needs to switch to the clicky hand cursor on hover
