### ISSUE TITLE
Ideas for a data portal

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW-Website#271]
Collector issue for the idea of making our site less of an info dump & more of a portal to data, reports, and tools— drop links and ideas here!

**Comment by Frijol** [comment]
I really like the clarity of flow for this site, it feels like I'm going down a decision tree to find what I'm looking for—there are never too many options to process & there's minimal text https://ivan-imperial.org/ hat tip to @csellers for finding this

**Comment by ericnost** [comment]
less well done, but maybe a similar idea: https://geography.wisc.edu/hazardouswaste/

**Comment by ericnost** [comment]
https://ericnost.github.io/EEW-Portal-Test/map.html

plus

https://forms.gle/6dXnZABpij9QyBRk6

**Comment by Frijol** [comment]
The COVID Tracking Project has some thoughtful design around maps, special callout to alternative maps of the USA by state so that even RI is clickable on mobile by people with motor tracking issues https://covidtracking.com/data/charts

**Comment by Frijol** [comment]
Demo Shiny app: https://sangmeng.shinyapps.io/COVID19/

**Comment by Frijol** [comment]
Of course https://ejscreen.epa.gov/mapper/ should be on this list
