### ISSUE TITLE
Add how-to videos to site

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW-Website#272]
https://drive.google.com/file/d/1khylWeodis4BQwup_dLZJCNnr_qzuNmy/view?usp=sharing
https://drive.google.com/file/d/1DFUZQ_hVejJbSk_R43-M395ZQum8DW33/view?usp=sharing

**Comment by Frijol** [comment]
Youtube links to same videos (they could use descriptions in Youtube):
https://youtu.be/KJuEK89Y73c
https://youtu.be/Q0iXOn-dY1g

**Comment by ericnost** [comment]
Add Megan's demo of how to use R Markdown template to generate a reportcard (in progress)
