### ISSUE TITLE
Update map to include additional reports

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW-Website#280]
Update map on https://www.staging.environmentalenforcementwatch.org/ to include new reports listed at https://docs.google.com/spreadsheets/d/1jdPCoJxfdCLqVg8rAlPbV4T0mUuw6BG-e1M08Ls0fQw/edit#gid=0

@ericnost if you drop a file here I can put it into the site!

Sophia also suggested slightly larger typeface in the legend

**Comment by Frijol** [comment]
![updated_map](https://user-images.githubusercontent.com/454690/115908146-a2121400-a41e-11eb-8176-f4bbe76589a4.png)

**Comment by ericnost** [comment]
![updated_map](https://user-images.githubusercontent.com/6888951/115912745-b6193e00-a43d-11eb-8ad1-15473b228a40.png)
