### ISSUE TITLE
Update to new Open Hour poster image?

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW-Website#281]
I think there was a plan to change the image? I have the current one up at https://www.staging.environmentalenforcementwatch.org/ but if you drop an updated one here I can swap it into the site

**Comment by lourdesvera** [comment]
[Here is the updated one in the gdrive folder](https://drive.google.com/file/d/1vugSiIfHH3M-jua0IXSHmdRF-_cEyQcb/view?usp=sharing)
