### ISSUE TITLE
Favicon not propagating to remote site

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW-Website#29]
Works fine on local but not on gh-pages hosted site

**Comment by plastichotsprings** [comment]
![image](https://user-images.githubusercontent.com/4603869/92644208-ff52be00-f2b0-11ea-8315-886a5704845b.png)
This seems to have something to do with it, but unclear why this is happening.

**Comment by plastichotsprings** [comment]
Fixed in https://github.com/edgi-govdata-archiving/EEW-Website/commit/268fafade7c6bb50bb69569e6c3b4b524b317b42
