### ISSUE TITLE
Tweak fonts/sizes/styling throughout site

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW-Website#4]
![Screen Shot 2020-08-12 at 12 49 36 PM](https://user-images.githubusercontent.com/454690/90060934-493c8a00-dc9a-11ea-8d7a-094d123293b0.png)

We will need to set styles across the site, check for

* [x] Overlapping fields
* [x] Blurry images
* [x] Legible text
* [x] Aesthetically pleasing

Specific needs:
* [x] Line spacing looks a bit off in paragraphs, need better legibility
* [ ] 2-col layout for events (use Markdown tables with invisible outlines?)
* [x] The bright red links are alarming, use color scheme from EDGI Style Guide?
* [x] Huge EEW icon on main page should be swapped for the more standard EEW icon (words spelled out) at a smaller size
* [x] Bold font not rendering (see homepage)
* [x] UL bullets not rendering (see homepage)
* [ ] Workshop tracks layout is specific, do a Markdown table again w/ report-making above
* [x] Shouldn't have a big space between content and footer

**Comment by plastichotsprings** [comment]
Took care of all of these except the column layout. It looks like Markdown tables won't do the trick for this (at least, when I tried it)
