### ISSUE TITLE
Remove unfinished pieces from homepage

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW-Website#44]
![Screen Shot 2020-09-02 at 1 48 40 PM](https://user-images.githubusercontent.com/454690/92035070-044cc600-ed23-11ea-95db-b7e66e8d97f0.png)
![Screen Shot 2020-09-02 at 1 48 36 PM](https://user-images.githubusercontent.com/454690/92035083-07e04d00-ed23-11ea-82d7-522176601584.png)

**Comment by plastichotsprings** [comment]
I removed the placeholder for the visualization. Are we sure that we want to remove the "who we are" block? The design ideation/persona exercises that we did as a group suggested that you all wanted it to be very obvious to visitors who is involved with EEW. Let me know how you want to proceed @lourdesvera @Frijol
