### ISSUE TITLE
Create Press page

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW-Website#5]
Should have:

* Who to contact – EEW email address, find on current EEW page
* Image assets
  * People doing the event – @gabrielletrudo can you collect this during the next event?
  * A choice snapshot from a report – @mraisle and/or @calderEDJ can you choose one or two & put it in this issue?
  * Branding – @calderEDJ @gabrielletrudo where can this be found to be put on the Press page?

**Comment by Frijol** [comment]
If folks can paste all of the materials here I can put them up on the page

**Comment by mraisle** [comment]
Will screenshot and put a page here when ready !

**Comment by Frijol** [comment]
Ping on this – here's what I came up with:

![Screen Shot 2020-09-02 at 4 26 57 PM](https://user-images.githubusercontent.com/454690/92047245-7cbe8180-ed39-11ea-972f-3a68ff566e5b.png)
![Screen Shot 2020-09-02 at 4 27 03 PM](https://user-images.githubusercontent.com/454690/92047248-7f20db80-ed39-11ea-84d9-3b67f5e5d650.png)

What other assets might press want to use?
