### ISSUE TITLE
Adding links to the Repo on the website Sept 11

### ISSUE THREAD

**Issue by lesliealanis** [edgi-govdata-archiving/EEW-Website#54]
We need to add links to the repo on the website

**Comment by Frijol** [comment]
Hi Leslie, can you give more details here please?

**Comment by lesliealanis** [comment]
Hi @Frijol I wasn't sure what this issue meant either, should I go ahead and ask in the general channel?

**Comment by Frijol** [comment]
Sure!

**Comment by Frijol** [comment]
Closing, please reopen if there is a concrete ask. @calderEDJ tagging you in case this is something to add in the Events page copy
