### ISSUE TITLE
Having the first draft of EEW website sept 18

### ISSUE THREAD

**Issue by lesliealanis** [edgi-govdata-archiving/EEW-Website#55]
Having an EEW website draft ready by sept 18, Do we have a draft ready? @ozzmotic @Frijol @calderEDJ

**Comment by plastichotsprings** [comment]
Yup here it is https://edgi-govdata-archiving.github.io/EEW-Website/

**Comment by Frijol** [comment]
I'm on board with this, tbh I think we could switch to it now if we wanted to
