### ISSUE TITLE
Second/Final Website review Sept 24

### ISSUE THREAD

**Issue by lesliealanis** [edgi-govdata-archiving/EEW-Website#57]
Is this a good day to review the eew website draft #55 ?

**Comment by Frijol** [comment]
First review today in EEW meeting!

**Comment by Frijol** [comment]
But yes let's do another Sep 22

**Comment by Frijol** [comment]
Hm, I'm not well prepared for this. Thursday might be a better idea

**Comment by lesliealanis** [comment]
Just changed it here and on the mural calendar
