### ISSUE TITLE
Copy for website drafted

### ISSUE THREAD

**Issue by lesliealanis** [edgi-govdata-archiving/EEW-Website#58]
Not sure what this issue refers too, this is how its listed in the [September notes doc](https://docs.google.com/document/d/1QUrKzPTCSLEssqGPiQbLK507I519tYls9EKERXg-Sp4/edit#heading=h.s8auecfa33q0)

**Comment by lesliealanis** [comment]
@Frijol do we have a tentative day for this issue?

**Comment by Frijol** [comment]
I think @saraannwylie and @calderEDJ might be working on this this week but it would be good to check in with them

**Comment by Frijol** [comment]
closing this issue in favor of https://github.com/edgi-govdata-archiving/EEW-Website/issues/61
