### ISSUE TITLE
Copy for website finalized Oct 2nd?

### ISSUE THREAD

**Issue by lesliealanis** [edgi-govdata-archiving/EEW-Website#61]
I'm also not sure what this issue means but its listed like this in the September notes doc, I know its linked to #58

**Comment by Frijol** [comment]
Issues that are ~part of this:

https://github.com/edgi-govdata-archiving/EEW-Website/issues/156
https://github.com/edgi-govdata-archiving/EEW-Website/issues/144
https://github.com/edgi-govdata-archiving/EEW-Website/issues/154

**Comment by Frijol** [comment]
superseded by https://github.com/edgi-govdata-archiving/EEW-Website/issues/177
