### ISSUE TITLE
Formatting of 5 workshop icons/text on home page

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW-Website#71]
from @saraannwylie

**Comment by Frijol** [comment]
@saraannwylie do you mean center-aligned?

**Comment by lesliealanis** [comment]
linked with #82 are these the same thing @Frijol @calderEDJ?

**Comment by Frijol** [comment]
* Make text lengths the same/shorter?
* Hide text as hovertext?
* Story gathering text should not cut off (currently does)
* Put it onto another page "our approach" which includes goals too?

Putting this conversation off behind design of homepage

**Comment by Frijol** [comment]
Maybe we should bring back this header: 

# Strong environmental regulation is important, but it’s only as good as its enforcement.

**Comment by Frijol** [comment]
Closed in https://github.com/edgi-govdata-archiving/EEW-Website/pull/105
