### ISSUE TITLE
Spacing apart the donation buttons and the mailing list subscription buttons

### ISSUE THREAD

**Issue by lesliealanis** [edgi-govdata-archiving/EEW-Website#80]
Placing the donation buttons and the mailing list subscription apart so that its made evident that they are different things
https://edgi-govdata-archiving.github.io/EEW-Website/reports
![image](https://user-images.githubusercontent.com/66931792/93275322-9a083c80-f78a-11ea-9088-6d20b21db867.png)

**Comment by Frijol** [comment]
done
