### ISSUE TITLE
Clean up footer

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW-Website#96]
Discussing with @calder @crgreenleaf @ozzmotic @lesliealanis @lightandluck 

Let's use this issue to discuss design experiments/ideas here. Note that this isn't launch-blocking

**Comment by crgreenleaf** [comment]
Do we move the hashtags from the footer to the press page?

**Comment by Frijol** [comment]
@crgreenleaf anything you still want to mess with here? I think it looks pretty good tbh
