### ISSUE TITLE
Homepage Design

### ISSUE THREAD

**Issue by lesliealanis** [edgi-govdata-archiving/EEW-Website#97]
Questions to discuss:
- Should we keep what is there already or make it more report card focused?
- Should we include the text under the different tract icons or should we make the text appear when people hover over them?
-  Is there too much text in this page?

**Comment by Frijol** [comment]
We'll cover this in tomorrow's website exercise!

**Comment by Frijol** [comment]
We used [this mural](https://app.mural.co/invitation/mural/edgi7967/1600897580981?sender=envirodgi2469&key=e1a1ece9-4521-40bc-9604-208d0fd53362 ) and [these notes](https://docs.google.com/document/d/1QUrKzPTCSLEssqGPiQbLK507I519tYls9EKERXg-Sp4/edit#heading=h.65war2hywvag) to talk about what the homepage should look like for launch. @calderEDJ is now going to use that discussion to generate two draft homepages in the mural: one for launch, and one for EEW more broadly

**Comment by Frijol** [comment]
Locking down site design on Mural by 9am PST tomorrow
